##############################################
app:
  name: reservation
  image: jse0111/autto-reservation-service-amd64:1.0 #hikikiki/autto-backend-reservation

replicaCount: 1

########service###############################
service:
  type: LoadBalancer
  port: 8083
  targetPort: 8083

########configmap, secret###############################

envFrom:
  - configMapRef:
      name: reservation-config
  # - secretRef: 
  #     name: reservation-secret
