replicaCount: 1
namespace: helm-backend
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: auttoever.com
      paths:
        - path: /api/v1/reservation
          pathType: Prefix
  tls: []
image:
  repository: auttto/reservation-service
  tag: "1.0.1.110"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8083
  targetPort: 8083
mysql:
  host: "52.78.50.11"
  port: "3306"
  database: "ReservationDB"
  user: "root"
  password: "1234"
cors:
  allow: "http://localhost:3000,http://localhost:8080"
kafka:
  server: "52.78.50.11:9093"
  consumer_group: "inventory-group"
  topic: "inventory-events"
spring:
  profile: "prod"
reservation:
  url: "http://auttoever.com"
jwt:
  secret: "64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff"
server:
  port: "8083"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
