replicaCount: 1
namespace: autto-service
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: autto.ever.com
      paths:
        - path: /api
          pathType: Prefix
  tls: []
image:
  repository: autto.harbor.com/auttto/reservation-service
  tag: "1.0.1.129"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8083
  targetPort: 8083
mysql:
  host: "192.168.10.7"
  port: "3306"
  database: "ReservationDB"
  user: "root"
  password: "1234"
kafka:
  server: "192.168.10.11:9092, 192.168.10.12:9092"
  consumer_group: "inventory-group"
  topic: "inventory-events"
spring:
  profile: "prod"
reservation:
  url: "http://112.218.95.58:13005"
jwt:
  secret: "64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff"
server:
  port: "8083"
cors:
  origins: "http://autto.ever.com,http://112.218.95.58:13005"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
