##############################################
app:
  name: admin
  image: jse0111/autto-admin-service-amd64:1.0 #hikikiki/autto-backend-admin

replicaCount: 1

########service###############################
service:
  type: LoadBalancer
  port: 8084
  targetPort: 8084

########configmap, secret###############################

envFrom:
  - configMapRef:
      name: admin-config
  # - secretRef: 
  #     name: admin-secret
