replicaCount: 1
namespace: autto-service
ingress:
  enabled: true
  className: nginx # nginx-ingress-controller 사용
  annotations: {}
  hosts:
    - host: auttoever.com # 실제 도메인으로 변경
      paths:
        - path: /admin
          pathType: Prefix
  tls: []
image:
  repository: autto.harbor.com/auttto/admin-service
  tag: "1.04.134"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8084
  targetPort: 8084
mysql:
  host: "192.168.10.7"
  port: "3306"
  database: "ProductDB"
  username: "root"
  password: "1234"
kafka:
  servers: "192.168.10.11:9092, 192.168.10.12:9092"
  consumer_group: "inventory-group"
jwt:
  secret: "64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff"
minio:
  endpoint: "http://192.168.10.8:9000"
  accessKey: "E9SGkOFznld2tjtykT13"
  secretKey: "x2BpH0xu0fbeRdRYl7Crgzc7OK9xVnKnOcFI8Y2t"
  bucket: "dev-test"
cors:
  origins: "http://auttoever.com"
server:
  port: "8084"
resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "500m"
    memory: "512Mi"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
