apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: {{ .Values.namespace }}
data:
  MYSQL_HOST: {{ .Values.mysql.host | quote }}
  MYSQL_PORT: {{ .Values.mysql.port | quote }}
  MYSQL_DATABASE: {{ .Values.mysql.database | quote }}
  MYSQL_USER: {{ .Values.mysql.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mysql.password | quote }}
  
  MAIL_HOST: {{ .Values.mail.host | quote }}
  MAIL_PORT: {{ .Values.mail.port | quote }}
  SPRING_MAIL_USERNAME: {{ .Values.mail.username | quote }}
  SPRING_MAIL_PASSWORD: {{ .Values.mail.password | quote }}
  
  REDIS_HOST: {{ .Values.redis.host | quote }}
  REDIS_PORT: {{ .Values.redis.port | quote }}
  
  JWT_SECRET: {{ .Values.jwt.secret | quote }}
  SERVER_PORT: {{ .Values.server.port | quote }}
  
  ALLOWED_ORIGINS: {{ .Values.cors.origins | quote }}
