apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: msa-user
  template:
    metadata:
      labels:
        app: msa-user
    spec:
      containers:
        - name: msa-user
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: MYSQL_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: MYSQL_PASSWORD
            - name: MAIL_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: MAIL_HOST
            - name: MAIL_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: MAIL_PORT
            - name: SPRING_MAIL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: SPRING_MAIL_USERNAME
            - name: SPRING_MAIL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: SPRING_MAIL_PASSWORD
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: REDIS_HOST
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: REDIS_PORT
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: JWT_SECRET
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: user-config
                  key: SERVER_PORT
