apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-app
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-app
    spec:
      containers:
      - name: {{ .Values.app.name }}-container
        image: {{ .Values.app.image }}
        {{- with .Values.envFrom }}
        envFrom:
          {{- toYaml . | nindent 12 }}
        {{- end }}
        