apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: msa-reservation
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: reservation-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: reservation-config
                  key: MYSQL_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: reservation-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: reservation-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: reservation-config
                  key: MYSQL_PASSWORD
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: reservation-config
                  key: ALLOWED_ORIGINS
            - name: KAFKA_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: reservation-config
                  key: KAFKA_SERVERS
            - name: KAFKA_CONSUMER_GROUP
              valueFrom:
                configMapKeyRef:
                  name: reservation-config
                  key: KAFKA_CONSUMER_GROUP
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: reservation-config
                  key: KAFKA_TOPIC
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: reservation-config
                  key: SPRING_PROFILES_ACTIVE
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: reservation-config
                  key: JWT_SECRET
            - name: RESERVATION_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: reservation-config
                  key: RESERVATION_SERVICE_URL
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: reservation-config
                  key: SERVER_PORT
