apiVersion: v1
kind: Service
metadata:
  name: reservation-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: msa-reservation
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}
