##############################################
app:
  name: query
  image: jse0111/autto-query-service-amd64:1.0 #hikikiki/autto-backend-query

replicaCount: 1

########service###############################
service:
  type: LoadBalancer
  port: 8082
  targetPort: 8082

########configmap, secret###############################

envFrom:
  - configMapRef:
      name: query-config
  # - secretRef: 
  #     name: query-secret
