replicaCount: 1
namespace: autto-service
ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    - host: auttoever.com
      paths:
        - path: /products
          pathType: Prefix
  tls: []
image:
  repository: autto.harbor.com/auttto/query-service
  tag: "1.0.2.119"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8082
  targetPort: 8082
mysql:
  host: "192.168.10.6"
  port: "3306"
  database: "ProductDB"
  user: "root"
  password: "1234"
jwt:
  secret: "64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff"
custom:
  url:
    reservation: "http://auttoever.com/api/v1/reservation"
server:
  port: "8082"
cors:
  origins: "http://auttoever.com"
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
