##############################################
app:
  name: user
  image: jse0111/autto-user-service-amd64:1.0 #hikikiki/autto-backend-user

replicaCount: 1

########service###############################
service:
  type: LoadBalancer
  port: 8081
  targetPort: 8081

########configmap, secret###############################

envFrom:
  - configMapRef:
      name: user-config
  # - secretRef: 
  #     name: user-secret
