replicaCount: 1
namespace: autto-service
# ingress:
#   enabled: true
#   className: nginx # nginx-ingress-controller 사용
#   annotations: {}
#   hosts:
#     - host: autto.ever.com # 실제 도메인으로 변경
#       paths:
#         - path: /auth
#           pathType: Prefix
#   tls: []
image:
  repository: autto.harbor.com/auttto/user-service
  tag: "0.0.3.128"
  pullPolicy: Always
service:
  type: ClusterIP
  port: 8081
  targetPort: 8081
mysql:
  host: "192.168.10.7"
  port: "3306"
  database: "UserDB"
  user: "root"
  password: "1234"
mail:
  host: "smtp.naver.com"
  port: "465"
  username: "et0709@naver.com"
  password: "w6978979"
redis:
  host: "192.168.10.9"
  port: "6379"
jwt:
  secret: "64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff"
server:
  port: "8081"
cors:
  origins: "http://autto.ever.com"
autoscaling:
  enabled: true # HPA 활성화 여부
  minReplicas: 1 # 최소 Pod 수
  maxReplicas: 5 # 최대 Pod 수
  targetCPUUtilizationPercentage: 80
