replicaCount: 3
image:
  repository: nginx
  pullPolicy: Always
  tag: 0.0.2.77
# 추후 프로메테우스 연결 시 작성
#podAnnotations:
#  prometheus.io/scrape: "true"
#  prometheus.io/path: "/metrics"
#  prometheus.io/port: "8080"

#podLabels:
#  environment: production
#  monitoring: enabled
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: user-service.local # 192.168.19.136
      paths:
        - path: /user-service
          pathType: Prefix
  # 인증서 설정
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
resources:
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "500m"
    memory: "512Mi"
livenessProbe:
  httpGet:
    path: /healthz
    port: http
readinessProbe:
  httpGet:
    path: /readiness
    port: http
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80
nodeSelector: {}
