apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MYSQL_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MYSQL_USERNAME
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MYSQL_PASSWORD
            - name: KAFKA_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: KAFKA_SERVERS
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: KAFKA_SERVERS
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: JWT_SECRET
            - name: MINIO_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MINIO_ENDPOINT
            - name: MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MINIO_SECRET_KEY
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: MINIO_BUCKET
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-config
                  key: SERVER_PORT
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
