replicaCount: 2
namespace: autto-service
configMap:
  name: frontend-config
# ingress:
#   enabled: true
#   className: "nginx"
#   annotations: {}
#   hosts:
#     - host: autto.ever.com
#       paths:
#         - path: /
#           pathType: Prefix
image:
  repository: autto.harbor.com/auttto/frontend
  pullPolicy: Always
  tag: "1.0.3.142"
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 3000
  targetPort: 3000
resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 500m
    memory: 512Mi
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
