apiVersion: apps/v1
kind: Deployment
metadata:
  name: query-deployment
  namespace: {{ .Values.namespace }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: msa-query
  template:
    metadata:
      labels:
        app: msa-query
    spec:
      containers:
        - name: msa-query
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: query-config
                  key: MYSQL_HOST
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: query-config
                  key: MYSQL_PORT
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: query-config
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                configMapKeyRef:
                  name: query-config
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: query-config
                  key: MYSQL_PASSWORD
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: query-config
                  key: ALLOWED_ORIGINS
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: query-config
                  key: JWT_SECRET
            - name: RESERVATION_URL
              valueFrom:
                configMapKeyRef:
                  name: query-config
                  key: RESERVATION_URL
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: query-config
                  key: SERVER_PORT